### ISSUE TITLE
Support returning response body from authentication

### ISSUE THREAD

**Issue by mdbooth** [gophercloud/gophercloud#2262]
The response from an authentication request to `/v3/auth/tokens` contains metadata about the authenticated principal which is not necessarily easy or even possible obtainable later. For example, when authenticating with application credentials clouds.yaml might contain:

```yaml
clouds:
  mycloud:
    auth_type: v3applicationcredential
    auth:
      auth_url: https://openstack.example.com/v3
      application_credential_id: <credential id>
      application_credential_secret: <credential secret>
    identity_api_version: 3
    region_name: regionOne
```

The authentication response contains both the authentication scope and the user object, neither of which can be obtained directly from clouds.yaml. We can't even retrieve this later by retrieving the application credential metadata because this requires knowing the user_id, which we don't have.

From a purely plumbing POV, to avoid asking the user to reimplement authentication using just an IdentityV3 client we need to update v2auth() and v3auth() to return the entire response body rather than just parsing the catalog from it. We might then need a new authentication API which exposes this to avoid breaking the existing API.
