### ISSUE TITLE
New CI jobs aren't running & Ironic job is failing

### ISSUE THREAD

**Issue by EmilienM** [gophercloud/gophercloud#2275]
Not sure why, but Zuul is not picking up the new layout and still try to run the old jobs that we did split.

**Comment by EmilienM** [comment]
@wangxiyuan @lingxiankong

I think we need a zuul reconfiguration (last time was early October). Is that something you could do?

Thanks

**Comment by EmilienM** [comment]
OpenLab zuul isn't picking up the latest config because of this error:
https://status.openlabtesting.org/config-errors

```
    terraform-provider-openstack/terraform-provider-openstack - .zuul.yaml (stable-website)

    Zuul encountered a syntax error while parsing its configuration in the
    repo terraform-provider-openstack/terraform-provider-openstack on
    branch stable-website.  The error was:

      The project "terraform-providers/terraform-provider-openstack" was not
      found.  All projects referenced within a Zuul configuration must first
      be added to the main configuration file by the Zuul administrator.

    The error appears in the following project stanza:

      project:
          name: terraform-providers/terraform-provider-openstack
          check:
            jobs:
              - terraform-provider-openstack-unittest
              - terraform-provider-openstack-acceptance-test
          recheck-newton:
            jobs:
              - terraform-provider-openstack-acceptance-test-newton
          recheck-ocata:
            jobs:
              - terraform-provider-openstack-acceptance-test-ocata
          recheck-pike:
            jobs:
              - terraform-provider-openstack-acceptance-test-pike
          recheck-queens:
            jobs:
              - terraform-provider-openstack-acceptance-test-queens
          recheck-rocky:
            jobs:
              - terraform-provider-openstack-acceptance-test-rocky
          recheck-stein:
            jobs:
              - terraform-provider-openstack-acceptance-test-stein
          recheck-trove:
            jobs:
              - terraform-provider-openstack-acceptance-test-trove
          recheck-designate:
            jobs:
              - terraform-provider-openstack-acceptance-test-designate
          recheck-lbaas:
            jobs:
              - terraform-provider-openstack-acceptance-test-lbaas
          recheck-fwaas:
            jobs:
              - terraform-provider-openstack-acceptance-test-fwaas

      in "terraform-provider-openstack/terraform-provider-openstack/.zuul.yaml@stable-website", line 1, column 3
```
