### ISSUE TITLE
v2: Support TrustID in AuthOptions (clouds.yaml)

### ISSUE THREAD

**Issue by pgaxatte** [gophercloud/gophercloud#3105]
The AuthOptions struct does not have a TrustID field making it impossible to use a trust with a `clouds.yaml` file.

This example works with the `openstack` CLI:

```
clouds:
  mycloud:
    auth:
      auth_url: https://...
      user_id: "..."
      password: "..."
      user_domain_name: "Default"
      trust_id: "XXXX"
    region_name: "RegionOne"
```

With gophercloud v2, I have to do this to use the trust:

```
authOptions, endpointOptions, tlsConfig, err := clouds.Parse()
authOptions.Scope = &gophercloud.AuthScope{
	TrustID: "XXX",
}
```
